name: Run Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Кэширование зависимостей
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('pom.xml') }}

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}

      # 2. Установка Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # 3. Установка зависимостей
      - name: Resolve dependencies
        run: mvn install -DskipTests

      # 4. Установка Playwright
      - name: Install Playwright browsers
        run: mvn exec:java -Dexec.mainClass="com.microsoft.playwright.CLI" -Dexec.args="install chromium"

      # 5. Запуск тестов
      - name: Run tests
        run: mvn test

      # 6. Загрузка результатов
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports/